### ISSUE TITLE
Error thrown when clicking in the background of a chart

### ISSUE THREAD

**Issue by pruhsert** [Servoy/svyChartJS#7]
When you click in the background (white area) of a chart, an error is thrown from within the handleClick method:

Cannot read property '_datasetIndex' of undefined
    at t.Controller.handleClick (http://localhost:8080/svychartjs/chart/chart.js:253:36)
    at t.Controller.handleEvent (http://localhost:8080/svychartjs/lib/js/Chart.js:12:2550)
    at t.Controller.eventHandler (http://localhost:8080/svychartjs/lib/js/Chart.js:12:2007)
    at a (http://localhost:8080/svychartjs/lib/js/Chart.js:12:1378)
    at HTMLCanvasElement.s.(anonymous function) (http://localhost:8080/svychartjs/lib/js/Chart.js:14:1782

the dataset returned is an empty array in that case, so dataset[0] yields nothing.

**Comment by tuanway** [comment]
A fix has been added.  Should be in next release.
